### ISSUE TITLE
This is not your osu! folder!

### ISSUE THREAD

**Issue by cyperdark** [OctoDumb/osu-mixer#1] opened 2020-01-26 12:46 UTC
https://i.imgur.com/5yZ13eP.png
https://i.imgur.com/4Y5JLbk.png

**Comment by uzervlad** [comment] 2020-01-26 12:54
That's really weird. Will have a look on that when I have time to work on it.

**Comment by uzervlad** [comment] 2020-02-07 20:49
Sorry for the long wait. I never got to encounter this bug, but it seems that @TheEZIC has the same problem. We'll investigate it soon

**Comment by uzervlad** [comment] 2020-02-08 16:37
Closing this issue, as now we both can't reproduce this bug. Will re-open it if we get more reports of the same bug.

For now, you can do this as a temporary solution: 
1. Go to your `AppData/Roaming/osu-mixer` folder

2. Create `osupath.txt` and put your osu! path there
**_Make sure to replace all_** `\` **_with_** `/`

**Comment by uzervlad** [comment] 2020-02-24 14:48
@cyperdark please check the latest commit and tell me if it still throws you any error

**Closed as completed** 2020-02-24 14:47 UTC
Labels: bug
